"""remove tags column from the tools table

Revision ID: cfff004b5d4f
Revises: 7d5e42af539b
Create Date: 2026-07-02 16:42:37.945932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfff004b5d4f'
down_revision = '7d5e42af539b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.drop_column('tagsy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tagsy', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
